### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by rjclarkewp007** [SuRGeoNix/BitSwarm#7]
Hi there

I have two questions.

1. I can't seem to get more than 3000Kb/s download speed :( Is this normal?
2. Is there a way to also seed the torrents while they are downloading?

I have integrated this into a small game launcher which will be downloading the game zip file and ideally i would like it to seed while downloading and also get the fastest download speeds possible.

When testing my torrent download using something like qbittorrent then i get full download speeds of 10Mb/s, but when I use my launcher with BitSwarm I get max 3Mb/s download speed.

Any ideas, please let me know.
thanks!

**Comment by SuRGeoNix** [comment]
Hey @rjclarkewp007

I have seen BitSwarm reaching 20MB/s so there is no upper limit. However, because it doesn't' fully support all the BEPs and mainly uTP protocol might that is the reason that you cannot get some times the same as qbittorrent (or because of seeding). Seeding is not implemented :(

When I will have time for another update I will try to implement those but not promised yet. (as currently my free time I'm trying to invest it in the other project Flyleaf)

**Comment by rjclarkewp007** [comment]
Thanks so much for the reply.

So I added this to my options and now I'm downloading at full speed! :) Yay!
opt.BlockRequests = 500;


It would be awesome if the seeding option was also there though. So when you have some time please implement that. :)
thanks again for all the hard work!

**Comment by SuRGeoNix** [comment]
Unfortunately, not yet. I have focus my free time on the other project lately (Flyleaf). It shouldn't act as you described. It keeps open connection only for the seeders that have something to offer but even for the 'no pieces' peers will retry to connect them and ask them again later.
